services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - sgcc-network
    container_name: sgcc-db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - sgcc-network
    container_name: sgcc-redis
    command: |
      redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  node:
    build:
      context: node
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - sgcc-network
    container_name: sgcc-node
    volumes:
      - ./node/src/config/swagger.yaml:/app/dist/config/swagger.yaml
      - ./node/src/config/casbin_model.conf:/app/dist/config/casbin_model.conf

  redoc:
    image: redocly/redoc:latest
    ports:
      - "8080:80"
    volumes:
      - ./node/src/config/swagger.yaml:/usr/share/nginx/html/swagger.yaml
    environment:
      - SPEC_URL=swagger.yaml
    depends_on:
      node:
        condition: service_started
    networks:
      - sgcc-network
    container_name: sgcc-redoc

networks:
  sgcc-network: