services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    networks:
      - sgcc-network
    container_name: sgcc-db
    restart: always

  redis:
    image: redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - sgcc-network
    container_name: sgcc-redis
    command: |
      redis-server /etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
    restart: always

  node:
    build:
      context: node
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - db
    networks:
      - sgcc-network
    container_name: sgcc-node
    volumes:
      - ./node/src/config/swagger.yaml:/app/dist/config/swagger.yaml
      - ./node/src/config/casbin_model.conf:/app/dist/config/casbin_model.conf

networks:
  sgcc-network: